spring:
  application:
    name: api
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://192.168.0.101:5432/stage_gate}
    username: ${DB_USERNAME:veloso}
    password: ${DB_PASSWORD:a#m2^wCowwFYg2cjtkUV}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloak.veloso-labs.dev/realms/stage-gate}

  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:105MB}

file:
  storage:
    type: ${FILE_STORAGE_TYPE:s3}
    s3:
      endpoint: ${S3_ENDPOINT:http://192.168.0.101:9000}
      access-key: ${S3_ACCESS_KEY:admin}
      secret-key: ${S3_SECRET_KEY:6xqWE*6JviC7!fvTCeb2}
      bucket: ${S3_BUCKET:stage-gate}
      region: ${S3_REGION:us-east-1}
    local:
      base-path: ${FILE_LOCAL_BASE_PATH:/tmp/stage-gate-files}
server:
  servlet:
    context-path: /api

